---
title: <h2> Universidade Federal Fluminense <br> Programa de formação de executivos <br> Finanças corporativas e mercado de capitais </h2>
lang: pt-br
subtitle: "Disciplina: Finanças com R - análise e otimização de carteiras"
author: "Marcus Ramalho"
language: 
  title-block-author-single: "Professor: "
---

## Bem vindos!

Sejam bem vindos à disciplina de **Finanças com R - análise e otimização de carteiras**. Neste curso, vamos aprender a utilizar a linguagem de programação R para análise de dados financeiros e otimização de carteiras de investimento. Se este é o seu primeiro contato com a linguagem R, não se preocupe! Vamos começar do zero e aprender juntos, na prática.

::: callout-important
## Você não precisará instalar nada no seu computador, mas caso queira, um guia do passo a passo para tal será disponibilizado oportunamente.
:::

O curso é dividido em duas aulas:

-   **Aula 1:**

    -   Apresentação do curso

    -   Introdução ao RStudio

    -   Introdução à programação no R

        -   Objetos, tipos de variáveis e operações

    -   Finanças com R

        -   Obtenção de dados financeiros

        -   Manipulação e visualização de dados

-   **Aula 2:**

    -   Revisão da aula anterior

    -   Risco

    -   Otimização de carteiras

    -   Dashboards com Quarto

## Referências

-   [**https://posit.cloud/**](https://posit.cloud/): Plataforma em nuvem para desenvolvimento colaborativo de projetos em R e Python.

-   [**https://uff-adm.notion.site/Instala-o-b5969aeda52045289c52db8fd833c6b3**](https://uff-adm.notion.site/Instala-o-b5969aeda52045289c52db8fd833c6b3): Guia de instalação do R e RStudio.

-   [**https://ser.uff.br/**](https://ser.uff.br/): Seminário internacional de estatística com R.

-   [**https://latin-r.com/pt/**](https://latin-r.com/pt/): Site da conferência LatinR, um evento sobre o uso da linguagem R na América Latina.

-   [**https://r4ds.had.co.nz/index.html**](https://r4ds.had.co.nz/index.html): Livro online "R for Data Science", um guia completo para aprender a usar o R para análise de dados.

-   [**https://cienciadedatos.github.io/pt-r4ds/**](https://cienciadedatos.github.io/pt-r4ds/): Tradução para o português do livro "R for Data Science" feita pela comunidade Brasileira de R.

-   [**https://cran.r-project.org/**](https://cran.r-project.org/): Repositório oficial de pacotes da linguagem R.

-   [**https://marcusramalho.tech/RinVSCode/**](https://marcusramalho.tech/RinVSCode/): Tutorial do professor Marcus Ramalho sobre como usar o R no Visual Studio Code.

-   [**https://github.com/nextmarte**](https://github.com/nextmarte): Perfil do GitHub do professor Marcus Ramalho.

-   [**https://posit.co/download/rstudio-desktop/**](https://posit.co/download/rstudio-desktop/): Página para download do RStudio Desktop, um ambiente de desenvolvimento integrado para a linguagem R.

-   [**https://quarto.org/**](https://quarto.org/): Site do Quarto, uma ferramenta de código aberto para criação de documentos científicos e técnicos.

-   <https://rpubs.com/Sergio_Garcia/intermediate_portfolio_analysis_r> - **Intermediate to Portfolio Analysis in R**